import QuizEngine, { QuizQuestion } from "@/components/quiz/QuizEngine";

const questions: QuizQuestion[] = [
  /* ── DRAPEAUX (Q1–12) ──────────────────────────────────── */
  {
    id: 1,
    question: "Que signifie le drapeau rouge ?",
    flagImg: "/flags/rouge.svg",
    flagAlt: "Drapeau rouge",
    options: [
      "Arrêt immédiat de la séance",
      "Danger — ralentir sans dépasser",
      "Véhicule lent sur la piste",
      "Avertissement pour conduite antisportive",
    ],
    correct: 0,
    explanation: "Le drapeau rouge ordonne l'arrêt immédiat de la séance. Tous les concurrents doivent ralentir et rejoindre les stands ou la grille selon les instructions du DC.",
  },
  {
    id: 2,
    question: "Le drapeau jaune AGITÉ signifie :",
    flagImg: "/flags/jaune.svg",
    flagAlt: "Drapeau jaune agité",
    options: [
      "Danger en amont — ralentir, pas de dépassement",
      "Danger immédiat — réduire l'allure, prêt à s'arrêter, pas de dépassement",
      "Arrêt immédiat de la séance",
      "Fin de zone de danger",
    ],
    correct: 1,
    explanation: "Le jaune AGITÉ signale un danger immédiat. Les concurrents doivent réduire leur allure et être prêts à s'arrêter. Le jaune FIXE signale un danger en amont, moins immédiat.",
  },
  {
    id: 3,
    question: "Que signifie le drapeau vert présenté en sortie de zone jaune ?",
    flagImg: "/flags/vert.svg",
    flagAlt: "Drapeau vert",
    options: [
      "Départ de la course",
      "La zone de danger est dégagée — reprendre le rythme normal",
      "La voiture de sécurité rentre aux stands",
      "L'autorisation de doubler est accordée",
    ],
    correct: 1,
    explanation: "Le drapeau vert indique que la zone de danger est dégagée. Les concurrents peuvent reprendre leur vitesse de course. En fin de FCY/Code 60, il est agité à TOUS les postes pendant 1 tour.",
  },
  {
    id: 4,
    question: "À quel concurrent présente-t-on le drapeau bleu ?",
    flagImg: "/flags/bleu.svg",
    flagAlt: "Drapeau bleu",
    options: [
      "Au leader en tête de course",
      "À un concurrent en difficulté mécanique",
      "À un concurrent sur le point d'être doublé par un pilote plus rapide",
      "Au dernier concurrent de la course",
    ],
    correct: 2,
    explanation: "Le drapeau bleu est présenté au concurrent qui va être doublé par un pilote plus rapide. Il doit laisser passer sans retarder inutilement.",
  },
  {
    id: 5,
    question: "Que signifie le drapeau noir et orange (« meatball ») ?",
    flagImg: "/flags/meatball.svg",
    flagAlt: "Drapeau meatball",
    options: [
      "Exclusion immédiate du concurrent",
      "La piste est contaminée par de l'huile",
      "Problème mécanique apparent — le concurrent doit rejoindre les stands",
      "Avertissement pour conduite antisportive",
    ],
    correct: 2,
    explanation: "Le meatball (noir et orange) est présenté avec le numéro du concurrent dont le véhicule présente un problème mécanique apparent dangereux. Il doit obligatoirement rentrer aux stands.",
  },
  {
    id: 6,
    question: "Que signifie le drapeau jaune et rouge rayé ?",
    flagImg: "/flags/jaune-rouge.svg",
    flagAlt: "Drapeau jaune et rouge rayé",
    options: [
      "Fin de session sur piste mouillée",
      "La piste est rendue glissante (huile, eau, débris...)",
      "Danger immédiat — arrêt de séance",
      "Véhicule lent sur la portion contrôlée",
    ],
    correct: 1,
    explanation: "Le drapeau jaune et rouge rayé signale que la piste est rendue glissante par de l'huile, de l'eau ou des débris. Les concurrents doivent adapter leur conduite.",
  },
  {
    id: 7,
    question: "Avec quoi accompagne-t-on toujours le drapeau noir (exclusion) ?",
    flagImg: "/flags/noir.svg",
    flagAlt: "Drapeau noir",
    options: [
      "Un drapeau rouge simultané",
      "Un panneau indiquant le numéro du concurrent exclu",
      "Un panneau « STOP »",
      "Un signal sonore",
    ],
    correct: 1,
    explanation: "Le drapeau noir est toujours accompagné d'un panneau portant le numéro du concurrent exclu. Ce signal ne concerne qu'un seul pilote à la fois.",
  },
  {
    id: 8,
    question: "Que signifie le drapeau blanc ?",
    flagImg: "/flags/blanc.svg",
    flagAlt: "Drapeau blanc",
    options: [
      "Fin de session",
      "Abandon / reddition",
      "Présence d'un véhicule lent sur la piste (SC, ambulance, concurrent en difficulté...)",
      "Piste complètement dégagée",
    ],
    correct: 2,
    explanation: "Le drapeau blanc signale la présence d'un véhicule lent sur la piste. En Rallye, son utilisation est FACULTATIVE selon le règlement FFSA.",
  },
  {
    id: 9,
    question: "Quel drapeau/panneau signale le Code 60 en FFSA circuit asphalte ?",
    flagImg: "/flags/code60.svg",
    flagAlt: "Code 60",
    options: [
      "Drapeau orange avec le chiffre « 60 »",
      "Drapeau violet avec un cercle blanc portant le chiffre « 60 »",
      "Drapeau rouge avec le chiffre « 60 »",
      "Panneau lumineux uniquement, sans drapeau",
    ],
    correct: 1,
    explanation: "Le Code 60 est signalé par un drapeau VIOLET avec un cercle blanc portant le chiffre 60. Il est d'abord agité à tous les postes sur ordre du DC, puis tenu fixe.",
  },
  {
    id: 10,
    question: "Le double drapeau jaune agité signifie :",
    flagImg: "/flags/jaune.svg",
    flagAlt: "Double drapeau jaune",
    options: [
      "Deux zones de danger successives",
      "Danger immédiat — voie totalement ou partiellement obstruée, prêt à s'arrêter",
      "La piste est fermée à tous les concurrents",
      "Fin de zone de danger imminente",
    ],
    correct: 1,
    explanation: "Le double drapeau jaune agité signale un danger immédiat grave, avec la voie totalement ou partiellement obstruée. C'est le signal le plus grave avant le drapeau rouge.",
  },
  {
    id: 11,
    question: "En circuit asphalte FFSA, le drapeau vert après une neutralisation Safety Car est présenté :",
    flagImg: "/flags/vert.svg",
    flagAlt: "Drapeau vert",
    options: [
      "À tous les postes simultanément",
      "Uniquement sur la ligne de relance",
      "Au poste le plus proche de l'incident résolu",
      "Par le DC en personne",
    ],
    correct: 1,
    explanation: "Lors d'une relance SC, le drapeau vert est présenté UNIQUEMENT sur la ligne de relance — jamais à tous les postes. C'est différent de la fin de FCY/Code 60 où il est agité partout.",
  },
  {
    id: 12,
    question: "À quel moment agite-t-on le drapeau damier ?",
    flagImg: "/flags/damier.svg",
    flagAlt: "Drapeau damier",
    options: [
      "Au moment du départ de la course",
      "Au passage de la voiture de sécurité en fin de course",
      "Au passage du vainqueur, puis de tous les concurrents suivants",
      "Uniquement au vainqueur, pas aux autres",
    ],
    correct: 2,
    explanation: "Le drapeau damier est agité vigoureusement au passage du vainqueur, puis présenté à tous les concurrents suivants. Il marque la fin officielle de l'épreuve.",
  },

  /* ── PROCÉDURES (Q13–24) ───────────────────────────────── */
  {
    id: 13,
    question: "Lors du déploiement du Safety Car, les concurrents sont-ils autorisés à se dépasser ?",
    options: [
      "Oui, si la piste est dégagée devant eux",
      "Non, tout dépassement est strictement interdit",
      "Oui, uniquement pour rejoindre leur position d'origine",
      "Oui, avec l'accord explicite du DC",
    ],
    correct: 1,
    explanation: "Sous Safety Car, aucun dépassement n'est autorisé. Les concurrents se regroupent dans l'ordre de course derrière le premier concurrent, lui-même derrière le SC.",
  },
  {
    id: 14,
    question: "Quelle procédure FFSA impose 80 km/h sans déployer physiquement un véhicule de sécurité ?",
    options: [
      "Safety Car (SC)",
      "Code 60",
      "Full Course Yellow (FCY)",
      "Virtual Safety Car (VSC)",
    ],
    correct: 2,
    explanation: "Le FCY impose 80 km/h à tous les concurrents sans qu'un véhicule de sécurité soit physiquement sur la piste. C'est une neutralisation légère, plus rapide que le SC.",
  },
  {
    id: 15,
    question: "Le Virtual Safety Car (VSC) est-il utilisé dans les compétitions FFSA nationales ?",
    options: [
      "Oui, depuis 2022",
      "Non, c'est une procédure propre à la FIA/F1",
      "Oui, sur les circuits homologués Grade 1",
      "Oui, il remplace le FCY",
    ],
    correct: 1,
    explanation: "Le VSC est une procédure propre à la FIA/F1. Dans les compétitions FFSA nationales, son équivalent est le FCY (Full Course Yellow) à 80 km/h.",
  },
  {
    id: 16,
    question: "Lors d'un départ arrêté en FFSA, comment le signal de départ est-il donné ?",
    options: [
      "Par un drapeau vert agité par le directeur de course",
      "Par l'extinction des feux rouges",
      "Par un signal sonore (klaxon)",
      "Par un feu vert allumé",
    ],
    correct: 1,
    explanation: "Lors d'un départ arrêté, les feux rouges s'allument un à un puis s'éteignent simultanément pour donner le départ. L'extinction est le signal officiel.",
  },
  {
    id: 17,
    question: "La voie des stands (pit lane) reste-t-elle ouverte sous Safety Car en FFSA ?",
    options: [
      "Non, elle est fermée pendant toute la durée du SC",
      "Oui, sauf instruction contraire du DC",
      "Uniquement pour les interventions médicales",
      "Fermée uniquement lors du premier tour de SC",
    ],
    correct: 1,
    explanation: "En circuit asphalte FFSA, la voie des stands reste ouverte sous Safety Car sauf instruction contraire du DC. Idem sous FCY.",
  },
  {
    id: 18,
    question: "Sous Code 60, chaque tour effectué à vitesse réduite :",
    options: [
      "Ne compte pas dans le nombre total de tours",
      "Compte comme un tour de course normal",
      "Compte pour la moitié d'un tour",
      "Dépend du règlement particulier de l'épreuve",
    ],
    correct: 1,
    explanation: "Sous Code 60, chaque tour effectué à 60 km/h compte comme un tour de course normal. La course n'est pas suspendue, elle est neutralisée à vitesse réduite.",
  },
  {
    id: 19,
    question: "La fin de la procédure FCY est signalée par :",
    options: [
      "Un drapeau vert fixe à tous les postes",
      "Un drapeau vert agité pendant 1 tour à tous les postes",
      "Le simple retrait du panneau « FCY »",
      "Un signal radio uniquement",
    ],
    correct: 1,
    explanation: "La fin de FCY est signalée par un drapeau vert AGITÉ pendant 1 tour à TOUS les postes, permettant à tous les concurrents de constater la reprise de course.",
  },
  {
    id: 20,
    question: "En course de côte, un commissaire peut-il déclencher le drapeau rouge de sa propre initiative ?",
    options: [
      "Non, uniquement sur ordre du DC par radio",
      "Oui, en cas de danger immédiat mettant des vies en danger",
      "Oui, pour tout incident visible depuis son poste",
      "Non, jamais — même en situation d'urgence",
    ],
    correct: 1,
    explanation: "En course de côte, le commissaire peut déclencher le rouge de sa propre initiative uniquement en cas de danger immédiat menaçant des vies. Il doit immédiatement en informer le DC par radio.",
  },
  {
    id: 21,
    question: "Lors d'une FCY, le panneau « FCY » est présenté :",
    options: [
      "Uniquement sur la ligne de départ/arrivée",
      "À tous les postes simultanément avec le drapeau jaune",
      "Uniquement aux postes proches de l'incident",
      "Par le Safety Car sur son panneau arrière",
    ],
    correct: 1,
    explanation: "Lors d'une FCY, chaque poste agite un drapeau JAUNE et présente simultanément le panneau « FCY ». La combinaison des deux signaux à tous les postes est obligatoire.",
  },
  {
    id: 22,
    question: "Lors d'un Safety Car, à quel signal les pilotes savent-ils que la relance est imminente ?",
    options: [
      "Le SC allume des feux verts",
      "Le SC éteint ses feux orange clignotants",
      "Un drapeau vert est montré à tous les postes",
      "Un signal sonore retentit depuis la ligne",
    ],
    correct: 1,
    explanation: "Le Safety Car ÉTEINT ses feux orange clignotants sur la ligne de relance pour signaler que la relance est imminente. Le drapeau vert n'est ensuite présenté que sur cette ligne.",
  },
  {
    id: 23,
    question: "Lors d'un drapeau rouge, les concurrents doivent :",
    options: [
      "S'arrêter immédiatement là où ils se trouvent",
      "Rejoindre les stands à vitesse très réduite sans dépasser",
      "Continuer à vitesse normale jusqu'à la ligne",
      "Suivre le Safety Car jusqu'aux stands",
    ],
    correct: 1,
    explanation: "Lors d'un drapeau rouge, les concurrents doivent rejoindre les stands à vitesse très réduite sans dépasser. Ils ne doivent pas s'arrêter brutalement sur la piste.",
  },
  {
    id: 24,
    question: "En Karting, comment le drapeau bleu est-il présenté par la DC ?",
    flagImg: "/flags/bleu.svg",
    flagAlt: "Drapeau bleu",
    options: [
      "Tenu FIXE uniquement",
      "AGITÉ uniquement",
      "Au choix FIXE ou AGITÉ selon l'urgence",
      "Non utilisé en Karting",
    ],
    correct: 1,
    explanation: "En Karting, le drapeau bleu est présenté AGITÉ uniquement par la DC. Il n'existe pas de variante FIXE en Karting, contrairement à d'autres disciplines.",
  },

  /* ── LICENCES & INSTITUTIONS (Q25–33) ─────────────────── */
  {
    id: 25,
    question: "Quelle est la première licence commissaire délivrée par la FFSA ?",
    options: [
      "EICOB",
      "ENCOC",
      "Commissaire B",
      "OFS",
    ],
    correct: 1,
    explanation: "L'ENCOC (Commissaire C) est la première licence commissaire FFSA. Elle permet d'officier sur des épreuves nationales sous supervision. C'est le point d'entrée de la carrière de commissaire automobile.",
  },
  {
    id: 26,
    question: "Avec quelle licence peut-on officier sur des épreuves FIA internationales ?",
    options: [
      "ENCOC",
      "Commissaire A",
      "EICOB",
      "OFS",
    ],
    correct: 2,
    explanation: "L'EICOB permet d'officier sur des épreuves FIA dans toute l'Europe. C'est la licence supérieure à l'ENCOC dans le cursus FFSA.",
  },
  {
    id: 27,
    question: "Que signifie FFSA ?",
    options: [
      "Fédération Française des Sports Automobiles",
      "Fédération Française du Sport Automobile",
      "Fédération Française de Sécurité Automobile",
      "Fédération Française des Sports d'Asphalte",
    ],
    correct: 1,
    explanation: "FFSA signifie Fédération Française du Sport Automobile. Elle organise et réglemente les compétitions automobiles en France et délivre les licences des commissaires auto.",
  },
  {
    id: 28,
    question: "Quelle fédération gère les compétitions moto en France et délivre les licences OFS/OFF ?",
    options: [
      "FFSA",
      "FIA",
      "FFM",
      "ASA",
    ],
    correct: 2,
    explanation: "La FFM (Fédération Française de Motocyclisme) est l'équivalent de la FFSA pour les compétitions moto. Elle délivre les licences OFS et OFF pour les commissaires moto.",
  },
  {
    id: 29,
    question: "Que signifie ASA en sport automobile français ?",
    options: [
      "Autorité Sportive Automobile",
      "Association Sportive Automobile (locale)",
      "Administration des Sports Automobiles",
      "Agence de Sécurité Automobile",
    ],
    correct: 1,
    explanation: "L'ASA est une Association Sportive Automobile locale, affiliée à la FFSA. C'est via l'ASA locale que les commissaires prennent leur licence et intègrent les équipes d'officiels.",
  },
  {
    id: 30,
    question: "Avant d'obtenir la licence ENCOC, quelle formation est obligatoire ?",
    options: [
      "Stage pratique de 2 jours sur circuit",
      "Formation en ligne (e-learning) sur la plateforme FFSA",
      "Formation au premier secours (PSC1)",
      "Stage théorique en présentiel de 3 jours",
    ],
    correct: 1,
    explanation: "Avant l'ENCOC, une formation en ligne (e-learning) sur la plateforme officielle FFSA est obligatoire. Elle couvre les fondamentaux du rôle de commissaire de piste.",
  },
  {
    id: 31,
    question: "Quelle est la tenue obligatoire pour un commissaire de circuit asphalte FFSA ?",
    options: [
      "Combinaison ignifugée homologuée FIA",
      "Combinaison en coton",
      "Chasuble haute visibilité",
      "Tenue imposée librement par l'organisateur",
    ],
    correct: 1,
    explanation: "En circuit asphalte FFSA, la combinaison en coton est obligatoire. Elle protège des projections et de la chaleur. Les combinaisons synthétiques sont proscrites en raison des risques d'inflammabilité.",
  },
  {
    id: 32,
    question: "Quel organisme mondial régit le sport automobile international (F1, WRC, WEC...) ?",
    options: [
      "FFSA",
      "FIA",
      "FFM",
      "ASA",
    ],
    correct: 1,
    explanation: "La FIA (Fédération Internationale de l'Automobile) est l'organisme mondial régissant le sport automobile international. Les commissaires EICOB peuvent officier sur ses épreuves.",
  },
  {
    id: 33,
    question: "Le terme « Steward » désigne :",
    options: [
      "Un commissaire de piste positionné sur les bordures",
      "Un commissaire sportif qui juge les incidents et inflige les pénalités",
      "Le directeur de course",
      "Le responsable médical de l'épreuve",
    ],
    correct: 1,
    explanation: "Les Stewards sont des commissaires sportifs chargés de juger les incidents et d'infliger les pénalités. Rôle distinct du commissaire de piste — les stewards n'interviennent pas physiquement sur la piste.",
  },

  /* ── ÉPREUVES, LEXIQUE & RÔLES (Q34–40) ──────────────── */
  {
    id: 34,
    question: "En rallye, qu'est-ce qu'une « épreuve spéciale » (ES) ?",
    options: [
      "Une manche comptant double pour le championnat",
      "Une portion de route fermée à la circulation, chronométrée",
      "Une épreuve de qualifications avant le rallye principal",
      "Un secteur chronométré ouvert à la circulation",
    ],
    correct: 1,
    explanation: "L'épreuve spéciale (ES) est une portion de route fermée à la circulation sur laquelle les équipages s'affrontent en temps. Elle est chronométrée du départ à l'arrivée.",
  },
  {
    id: 35,
    question: "Que signifie « parc fermé » ?",
    options: [
      "Une zone où les spectateurs sont interdits",
      "Zone sécurisée après la course où aucune intervention mécanique n'est autorisée sans permission",
      "Le parking réservé aux commissaires",
      "La zone de contrôle technique avant course",
    ],
    correct: 1,
    explanation: "Le parc fermé est une zone sécurisée où les véhicules sont parqués après la course ou les qualifications. Aucune intervention mécanique n'est autorisée sans permission des commissaires techniques.",
  },
  {
    id: 36,
    question: "Qu'est-ce que le « scratch » en rallye ?",
    options: [
      "Le meilleur temps absolu sur une spéciale, toutes catégories confondues",
      "Le temps de référence pour les pénalités de retard",
      "La vitesse moyenne de l'épreuve spéciale",
      "Le premier concurrent à l'arrivée dans sa catégorie",
    ],
    correct: 0,
    explanation: "Le scratch est le meilleur temps absolu sur une épreuve spéciale, toutes catégories confondues. Le concurrent qui réalise le scratch est le plus rapide sur la spéciale.",
  },
  {
    id: 37,
    question: "Qu'est-ce qu'un « drive-through » (penalty) ?",
    options: [
      "Un arrêt aux stands pour ravitaillement obligatoire",
      "Une pénalité consistant à traverser la pit lane sans s'arrêter",
      "Une technique de dépassement en ligne droite",
      "La procédure de sortie du Safety Car des stands",
    ],
    correct: 1,
    explanation: "Le drive-through est une pénalité obligeant le concurrent à traverser la voie des stands sans s'arrêter. Il doit être effectué dans un délai défini. Plus sévère : le Stop and Go où le pilote doit s'immobiliser.",
  },
  {
    id: 38,
    question: "Quel est le rôle du « Chef de poste » ?",
    options: [
      "Diriger l'ensemble de la course depuis la tour de contrôle",
      "Coordonner l'équipe de commissaires d'un poste et communiquer avec la DC",
      "Contrôler les véhicules avant la mise en grille",
      "Sanctionner les infractions des concurrents",
    ],
    correct: 1,
    explanation: "Le Chef de poste coordonne son équipe, maintient la communication radio avec la direction de course et prend les décisions d'intervention au niveau de son poste.",
  },
  {
    id: 39,
    question: "En circuit asphalte, combien de commissaires sont généralement mobilisés pour une épreuve nationale ?",
    options: [
      "10 à 20 commissaires",
      "60 à 150 commissaires",
      "200 à 300 commissaires",
      "Moins de 10 commissaires",
    ],
    correct: 1,
    explanation: "Un circuit asphalte national mobilise généralement 60 à 150 commissaires selon la taille du circuit. Un événement comme les 24 Heures du Mans peut en mobiliser plus de 400.",
  },
  {
    id: 40,
    question: "En circuit asphalte FFSA, à quelle vitesse maximum circule-t-on sous FCY, et à quelle vitesse sous Code 60 ?",
    options: [
      "FCY : 60 km/h — Code 60 : 80 km/h",
      "FCY : 80 km/h — Code 60 : 60 km/h",
      "FCY : 50 km/h — Code 60 : 60 km/h",
      "FCY et Code 60 : 60 km/h tous les deux",
    ],
    correct: 1,
    explanation: "En FFSA circuit asphalte : FCY = 80 km/h (contrôlé par chronométrage), Code 60 = 60 km/h (contrôlé par chronométrage). Le Code 60 est plus restrictif. Le VSC (FIA/F1) n'est pas utilisé en FFSA.",
  },
];

export default function QuizGeneralPage() {
  return (
    <QuizEngine
      title="Quiz général — 40 questions"
      questions={questions}
      backHref="/devenir-commissaire/quiz"
      backLabel="Retour aux quiz"
      reviewHref="/devenir-commissaire"
      reviewLabel="Espace pédagogique"
      glowColor="bg-blue-500/5"
    />
  );
}
